const levelsData = [
  {
     "type":"tinder-like",
     "question":"Угадай, фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/391205/art/6303693/5373463-XJBVKDMN-7.jpg",
              "width":770,
              "height":753
           },
           "type":"painting"
        }
     ]
  },
  {
     "type":"tinder-like",
     "question":"Угадай, фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/67871/art/2170314/1228269-QRTYSOAU-7.jpg",
              "width":770,
              "height":572
           },
           "type":"photo"
        }
     ]
  },
  {
     "type":"one-of-three",
     "question":"Найдите фото среди изображений",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/1009360/art/4323415/3393255-JXZQWNAL-7.jpg",
              "width":770,
              "height":770
           },
           "type":"painting"
        },
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/763890/art/2525455/1595398-HGTSPQFD-7.jpg",
              "width":770,
              "height":507
           },
           "type":"painting"
        },
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/894537/art/4145000/3214851-LPQQVQVW-7.jpg",
              "width":770,
              "height":468
           },
           "type":"photo"
        }
     ]
  },
  {
     "type":"two-of-two",
     "question":"Угадайте для каждого изображения фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/343280/art/463039/247474-UPMXLKGA-7.jpg",
              "width":770,
              "height":1155
           },
           "type":"photo"
        },
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/403015/art/2009033/1132294-7.jpg",
              "width":770,
              "height":577
           },
           "type":"painting"
        }
     ]
  },
  {
     "type":"two-of-two",
     "question":"Угадайте для каждого изображения фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/155519/art/1263027/574904-7.jpg",
              "width":468,
              "height":458
           },
           "type":"photo"
        },
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/662192/art/3418160/2488047-LKPHZZUA-7.jpg",
              "width":468,
              "height":458
           },
           "type":"painting"
        }
     ]
  },
  {
     "type":"tinder-like",
     "question":"Угадай, фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/96892/art/4024011/3093865-TCLGSUHD-7.jpg",
              "width":705,
              "height":455
           },
           "type":"photo"
        }
     ]
  },
  {
     "type":"tinder-like",
     "question":"Угадай, фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/337392/art/3980232/3050086-YZYSSYCI-7.jpg",
              "width":705,
              "height":455
           },
           "type":"painting"
        }
     ]
  },
  {
     "type":"two-of-two",
     "question":"Угадайте для каждого изображения фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/771197/art/2564064/1633985-OSDHCNJV-7.jpg",
              "width":468,
              "height":458
           },
           "type":"photo"
        },
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/301980/art/3611358/2681244-YFXGOCAP-7.jpg",
              "width":468,
              "height":458
           },
           "type":"painting"
        }
     ]
  },
  {
     "type":"two-of-two",
     "question":"Угадайте для каждого изображения фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/1053866/art/7726222/6794345-LKEYJMFH-7.jpg",
              "width":468,
              "height":458
           },
           "type":"painting"
        },
        {
           "image":{
              "url":"https://images.saatchiart.com/saatchi/55459/art/1852781/989883-UHMCBDVU-7.jpg",
              "width":468,
              "height":458
           },
           "type":"painting"
        }
     ]
  },
  {
     "type":"tinder-like",
     "question":"Угадай, фото или рисунок?",
     "answers":[
        {
           "image":{
              "url":"https://wl-brightside.cf.tsp.li/resize/728x/png/305/0ed/413a295c6daa5148d20baf04cc.png",
              "width":705,
              "height":455
           },
           "type":"painting"
        }
     ]
  }
]
  
  export  {levelsData};
